Init Consistency Checker dev branch to master
mskcc/cmo-metadb-consistency-checker pull request #7
Opened 2021-03-24 14:31 UTC by ao508

2021-03-26 02:30 UTC, n1zea144 reviewed
I like all the unit tests - I've left comments, mostly in the messaging handling code.  We can discuss over zoom.

2021-03-26 02:30 UTC, n1zea144 commented on src/main/java/org/mskcc/cmo/metadb/service/impl/MessageHandlingServiceImpl.java
> +                        File loggerFile = fileUtil.getOrCreateFileWithHeader(consistencyCheckerFailuresFilepath,
Should we move this to the constructor of NewIgoRequestHandler?

2021-03-26 02:30 UTC, n1zea144 commented on src/main/java/org/mskcc/cmo/metadb/service/impl/MessageHandlingServiceImpl.java
> +                            File loggerFile = fileUtil.getOrCreateFileWithHeader(consistencyCheckerFailuresFilepath,
Should we move this to the constructor of ConsistencyCheckerHandler?

2021-03-26 02:30 UTC, n1zea144 commented on src/main/java/org/mskcc/cmo/metadb/service/impl/MessageHandlingServiceImpl.java
> +                    File loggerFile = fileUtil.getOrCreateFileWithHeader(consistencyCheckerFailuresFilepath,
We should pull this out of the loop.

2021-03-26 02:30 UTC, n1zea144 commented on src/main/java/org/mskcc/cmo/metadb/service/impl/MessageHandlingServiceImpl.java
> +                ConsistencyCheckerRequest metadbConsistencyCheckRequest = metadbRequestConsistencyCheckerMessagesReceived.get(incomingRequestId);
I understand this has to do with a message that arrives, but arrives late.  I'm not following this section of code, lets discuss over zoom.

2021-03-29 19:18 UTC, ao508 commented on src/main/resources/log4j.properties.EXAMPLE
> +# Change INFO to DEBUG, if you want to see debugging info on underlying libraries we use.
done

2021-03-29 20:09 UTC, ao508 commented on src/main/java/org/mskcc/cmo/metadb/model/ConsistencyCheckerRequest.java
> +        SUCCESSFUL_PUBLISHING_TIME_EXCEEDED,
done

2021-03-29 20:09 UTC, ao508 commented on src/main/java/org/mskcc/cmo/metadb/ConsistencyCheckerApp.java
> +        System.out.println("Starting up MetaDB application...");
done

2021-03-30 14:21 UTC, n1zea144 requested changes

2021-03-30 14:21 UTC, n1zea144 commented on src/main/resources/application.properties.EXAMPLE
> +messaging.time_threshold_seconds=300
This default is already set in the code, should we leave it blank here?

2021-03-30 14:21 UTC, n1zea144 commented on src/main/java/org/mskcc/cmo/metadb/service/impl/MessageHandlingServiceImpl.java
> +            setupConsistencyCheckerHandler(messagingGateway, this);
Can we rename this to setupConsistencyCheckerSubscriber?

2021-03-30 14:21 UTC, n1zea144 commented on src/main/java/org/mskcc/cmo/metadb/service/impl/MessageHandlingServiceImpl.java
> +            setupIgoNewRequestHandler(messagingGateway, this);
Can we rename this to setupIgoNewRequestSubscriber?

2021-03-30 14:25 UTC, ao508 commented on src/main/java/org/mskcc/cmo/metadb/util/ConsistencyCheckerUtil.java
> +     * TODO?
i might just remove this for now

2021-03-30 14:29 UTC, ao508 commented
@n1zea144 requested changes have been made

2021-03-30 17:36 UTC, ao508 commented on src/main/java/org/mskcc/cmo/metadb/model/ConsistencyCheckerRequest.java
> + * @author ochoaa
add comment describing class

2021-03-30 17:37 UTC, n1zea144 commented on src/main/java/org/mskcc/cmo/metadb/service/impl/MessageHandlingServiceImpl.java
> +                        File loggerFile = fileUtil.getOrCreateFileWithHeader(
Lets pull this file open code out of this loop.

2021-03-30 17:38 UTC, n1zea144 commented on src/main/java/org/mskcc/cmo/metadb/service/impl/MessageHandlingServiceImpl.java
> +                            File loggerFile = fileUtil.getOrCreateFileWithHeader(
Lets pull this file open stuff out of this loop.

2021-03-30 21:10 UTC, n1zea144 requested changes

2021-03-30 21:10 UTC, n1zea144 commented on src/main/java/org/mskcc/cmo/metadb/service/impl/MessageHandlingServiceImpl.java
> +        this.loggerFile = fileUtil.getOrCreateFileWithHeader(
I didn't pick up on this until you made these changes, but do you know if BufferedWriter is thread safe?  That is, you have two threads writing to the same file, potentially at the same time.  My guess is that it is, but I would confirm.  You probably should put a call to flush here:
https://github.com/mskcc/cmo-metadb-common/blob/master/src/main/java/org/mskcc/cmo/common/impl/FileUtilImpl.java#L46

2021-03-31 15:55 UTC, merged